spring:
  datasource:
    url: jdbc:postgresql://c3nv2ev86aje4j.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d6vvdlv1a0klf5
    username: u4r4r6jfb177ac
    password: p94beb11e50714f127555f875ec44a7a0219ed649b9be0e47c825e10ea3b130f1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

twilio:
  account-sid: ACec8a1ed9e4ef4718c49e14ac1dda8733
  auth-token: 48edffa48f0cdb9f6abddfc9fbc9a9b3
  phone-number: +14173192867